#!/bin/sh
#
# mango-analytics Starts, Stops and Reload Mango Analitycs
#
# chkconfig: 2345 90 60
# description: Mango Analytics
# pidfile: pidfile=/var/run/django-cpwsgi.pid
#
# Thu Mar 13 2014 Israel Santana <isra@miscorreos.org>
# - Initial version
# - Get info from /etc/rc.local from Elastix 2.4
#
### BEGIN INIT INFO
# Provides:          mango-analytics
# Required-Start:    $network $mysql
# Required-Stop:     $network $mysql
# Should-Start:      httpd nginx
# Should-Stop:       httpd nginx
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Mango Analytics
# Description:          Mango Analytics Advanced PBX Reporting
### END INIT INFO

# Source function library.
. /etc/init.d/functions


VIRTUALENV=/opt/NEXTOR/tarificador
PROJECT=/opt/NEXTOR/tarificador/django-tarificador/tarificador
USER=asterisk
GROUP=asterisk
HOST=0.0.0.0
PORT=8123
PIDFILE=/var/run/django-cpwsgi.pid
CMD=$PROJECT/manage.py
OPTIONS="runwsgiserver port=$PORT daemonize=true pidfile=$PIDFILE \
	host=$HOST workdir=$PROJECT \
	server_user=$USER server_group=$GROUP"


RETVAL=0

getpid() {
    pid=`ps aux | grep tarificador | grep asterisk | awk '{print $2}'`
}

start() {
    echo -n $"Starting Mango Analytics: "
    getpid
    if [ -z "$pid" ]; then
    	. $VIRTUALENV/bin/activate
        python $CMD $OPTIONS > /dev/null
        RETVAL=$?
    fi
    if [ $RETVAL -eq 0 ]; then
        echo_success
    else
        echo_failure
    fi
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping Mango Analytics: "
    getpid
    RETVAL=$?
    if [ -n "$pid" ]; then
        PID=`cat $PIDFILE`
    	kill -15 $PID
    sleep 1
    getpid
    if [ -z "$pid" ]; then
        rm -f $PIDFILE
        echo_success
    else
        echo_failure
    fi
    else
        echo_failure
    fi
    echo
    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        getpid
        if [ -n "$pid" ]; then
                echo "Mango Analytics (pid $pid) is running..."
        else
                RETVAL=1
                echo "Mango Analytics is stopped"
        fi
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac

exit $RETVAL