#!/bin/bash
# description: FOP daemon
# process name: fop_start
# Author: Nick Ross
. /etc/init.d/functions
[ -f /usr/sbin/amportal ] || exit 0
FOP="/usr/sbin/amportal"
FXO="/usr/sbin/fxotune"
RETVAL=0
getpid() {
	pid=`ps -eo pid,comm | grep "op_server.pl" | awk '{ print $1 }'`
}
start() {
	echo -n $"Starting FOP: "
	getpid
	if [ -z "$pid" ]; then
		$FXO -s >dev/null
		$FOP start_fop > /dev/null
		RETVAL=$?
	fi
	if [ $RETVAL -eq 0 ]; then
		touch /var/lock/subsys/fop_start
		echo_success
	else
		echo_failure
	fi
		echo
		return $RETVAL
}
stop() {
	echo -n $"Stopping FOP: "
	getpid
	RETVAL=$?
	if [ -n "$pid" ]; then
		$FOP stop_fop > /dev/null
		sleep 1
		getpid
		if [ -z "$pid" ]; then
			rm -f /var/lock/subsys/fop_start
			echo_success
		else
			echo_failure
		fi
	else
		echo_failure
	fi
	echo
	return $RETVAL
}
# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		getpid
		if [ -n "$pid" ]; then
			echo "FOP (pid $pid) is running..."
		else
			RETVAL=1
			echo "FOP is stopped"
		fi
		;;
	restart)
		stop
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart}"
		exit 1
		;;
	esac
exit $RETVAL

